spring.datasource.url=jdbc:postgresql://localhost:5432/haushaltsbuch
spring.datasource.username=haushalt
spring.datasource.password=haushalt
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
